FORMAT: 1A
HOST: https://v1-dudetools.api.dudesolutions.io

USECOMMONSDKLIBRARY: TRUE
GENERATEASYNCCODE: TRUE
GENERATEINTERFACES: TRUE
USEMETHODPREFIX: TRUE
USEMODELPOSTFIX: FALSE
USECONTROLLERPOSTFIX: FALSE
USEENUMPOSTFIX: FALSE
USECONSTRUCTORSFORCONFIG: TRUE
CSHARPDEFAULTNAMESPACE: DSI.SDK.DudeTools
JAVADEFAULTNAMESPACE: io.dudesolutions.dudetools
BRANDLABEL: Dude Solutions, Inc.
USERAGENT: Dude SDK
NULLIFY404: TRUE
VALIDATEREQUIREDPARAMETERS: FALSE
COLLECTPARAMETERS: TRUE

# DudeTools Api

## Reference
Good reference document: https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/Polls%20API.md

## Authentication
*Dude File Api* uses OAuth v2 Authentication. First you create a new (or acquire existing) OAuth v2 token using [DudeAuth](https://www.dudeauth.com/).

New to *OAuth*?  Check out the [OAuth Bible](http://oauthbible.com/) for good reference material.

## Media Types
Where applicable this API uses the *JSON* media-type to represent resources.
Requests and responses with a message-body use plain JSON to set or update resources.

## Error States
Common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used throughout this API.
In addition to standard response codes the response object returned from the server during an exception event may contain additional information in the following JSON format:
{
 "message": "SOME MESSAGE",
 "dudeReferenceId": "3523845A-4729-4CCB-9E16-01DEADF6C2DF",
 "stackTrace": "Null, Typically"
 }

## Data Restriction
Depending on the access level granted to the calling client certain data elements throughout this API will be removed and not returned.

## Dates & Times
All dates and times are represented in [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) format. In addition, *Dude Security Api* will always provide [Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time).
The API is capable of parsing most date and time formats, however we do require UTC dates and times be provided from all calling systems. We highly recommend you utilize the ISO-8601 standard when communicating dates and time to the API as well.

## Known Issues
None at this time

## Documentation Notes
In Progress

# Group System Information
Check API System Information

## S.I. Check [/]
Retrieve api version, vitals, links, etc.

### GET

+ Response 200 (application/json)
    + Attributes (System Information)

# Group Heartbeat
Check health of dependent services

## Heartbeat Check [/heartbeat]
The heartbeat is exposed and provided to check for availability of the service.
Any response that does not provide a ```200 OK``` response code should be treated as an error.

### GET

+ Response 200 (application/json)
    + Headers

            X-Dude-Api-Limit: Unlimited or Number
            X-Dude-Api-Remaining: Unlimited or Number
            X-Dude-Api-Server: Api Server ID
    + Attributes (Heartbeat)

# Data Structures

## System Information (object)
Represents the System Information response.

### Properties
+ `application`: `DudeTools Api` (string, required) - The name of the application.
+ `version` : `1.0.0.0` (string, required) - The assembly version.
+ `apiVersion` : `1.0.0.0` (string, required) - The API version.
+ `vitals` (Heartbeat, required) - The state of the system dependencies.
+ `links` (array[System Links], required) - The API routes.

## System Links (object)
Represents the API routes.

### Properties
+ `endpoint` : `Accounts` (string, required) - The name of the endpoint.
+ `action` : `Get` (string, required) - The REST action.
+ `route` : `/accounts/{accountId}` (string, required) - The route to the endpoint.

## Heartbeat (object)
Represents a heartbeat response.

### Properties
+ `cachevitalcheck`: true (boolean, required) - Vital check to ensure Cache provider is online.
+ `filestoragevitalcheck`: true (boolean, required) - Vital check to ensure file storage provider is online.
+ `filedbvitalcheck`: true (boolean, required) - Vital check to ensure database provider is online.
+ `symantecantivirusprovidervitalcheck`: true (boolean, required) - Vital check to ensure malware provider is online.

## Base Collection Response (object)
Represents a paged response when bulk retrieving from a collection

### Properties
+ `page`: 1 (number, required) - {INT} The current page provided in the response data.
+ `pageSize`: 1000 (number, required) - {INT} The page size returned in the response data.
+ `dataSize`: 1000 (number, required) - {INT} The total records returned in the response.
+ `total`: 2000 (number, required) - {INT} The total number of records available in the collection.

## Audit (object)
Represents the audit fields

### Properties
+ `createdDateTime`: `2015-01-01T00:00:00.123Z` (string, optional) - {DATETIME} The date and time in ISO-8601 format the record was created.
+ `createdByUserId`: 1 (number, optional) - {INT} Information about the user who created the record.
+ `createdByApiClientId`: 1 (number, optional) - {INT} Information about the client who created the record.
+ `updatedDateTime`: `2015-01-01T00:00:00.123Z` (string, optional) - {DATETIME} The date and time in ISO-8601 format the record was last updated.
+ `updatedByUserId`: 1 (number, optional) - {INT} Information about the user who last modified the record.
+ `updatedByApiClientId`: 1 (number, optional) - {INT} Information about the client who last modified the record.
